ALTER TABLE product ADD COLUMN criticality VARCHAR(20) NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE product ADD COLUMN shelf_life_controlled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE product ADD COLUMN cold_chain_required BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sku ADD COLUMN brand VARCHAR(120);
ALTER TABLE sku ADD COLUMN pack_size VARCHAR(80);
ALTER TABLE sku ALTER COLUMN default_shelf_life_days DROP NOT NULL;

ALTER TABLE batch_inventory ALTER COLUMN expiry_date DROP NOT NULL;
