spring:
  datasource:
    url: jdbc:h2:mem:stockflow-sprint1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    locations: classpath:db/h2migration,classpath:db/h2support,classpath:db/devdata

logging:
  level:
    org.flywaydb: WARN
    org.hibernate.SQL: WARN
